#!/bin/sh

usage() {
  echo "Deploy to k8s"
  echo "  -h  Print usage instructions"
  echo "  -v  Version of the Docker image, i.e. the value of the tag"
}

while getopts ":hv:" opt; do
  case $opt in
  h)
    usage
    exit 0
    ;;
  v)
    VERSION=$OPTARG
    ;;
  \?)
    echo "Invalid option: -$opt" >&2
    usage
    exit 1
    ;;
  :)
    echo "Option -$opt requires an argument" >&2
    usage
    exit 1
    ;;
  esac
done
shift $(($OPTIND - 1))

if [ -z "$VERSION" ]; then
  VERSION=$(docker images --format "{{.Tag}}" hseeberger/bayer | sort -r | head -1)
  if [ -z "$VERSION" ]; then
    echo "ERROR: Cannot find any Docker image for hseeberger/bayer" >&2
    exit 1
  fi
elif [ -z $(docker images --format "{{.Tag}}" hseeberger/bayer | grep -x $VERSION) ]; then
  echo "ERROR: Unknown version $VERSION" >&2
  exit 1
fi
export VERSION
echo "Deploying version $VERSION"

current_dir=$(pwd)
cd $(dirname $0)
kustomize build | envsubst | kubectl apply -f -
cd $current_dir
